//! Correctness checks and versioned expectation manifests.

use anyhow::{Context, Result, bail};
use log_file_parser::{VdaAnalysisResult, validate_result};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::{
    collections::{BTreeMap, BTreeSet},
    fmt,
    fs::{self, File, OpenOptions},
    io::{Read, Write},
    path::Path,
};
use vda5050_analysis::{
    canonical_frame_counts, message_type_distribution_counts, record_counts, summarize,
};

/// The only expectation-manifest version understood by this CLI.
pub const MANIFEST_VERSION: u32 = 1;

/// Comment written before generated manifests to make their review status explicit.
pub const SNAPSHOT_NOTICE: &str = "# Candidate snapshot generated by the CLI; review it or compare it with an independent source before accepting it as ground truth.\n";

/// Stable source identity stored in an expectation manifest.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct SourceExpectation {
    pub size_bytes: u64,
    pub sha256: String,
}

/// Parser options that affect recognized records.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct ParserExpectation {
    pub root_topic: String,
}

/// Record totals captured by a manifest.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct RecordExpectation {
    pub total: u64,
    pub parsed: u64,
    pub ignored: u64,
}

/// Canonical DataFrame row counts captured by a manifest.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct FrameExpectation {
    pub index: u64,
    pub state: u64,
    pub visualization: u64,
    pub connection: u64,
    pub order: u64,
    pub instant_actions: u64,
}

/// Optional UTC timestamp bounds captured by a manifest.
#[derive(Clone, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct TimeRangeExpectation {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub start: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub end: Option<String>,
}

/// Stable aggregates captured by a manifest.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct ExpectedValues {
    pub records: RecordExpectation,
    pub frames: FrameExpectation,
    pub failures: BTreeMap<String, u64>,
    pub message_type_distribution: BTreeMap<String, u64>,
    pub unique_robots: u64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub time_range_utc: Option<TimeRangeExpectation>,
}

/// A versioned, source-bound expectation manifest.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct ExpectedManifest {
    pub manifest_version: u32,
    pub source: SourceExpectation,
    pub parser: ParserExpectation,
    pub expected: ExpectedValues,
}

/// The source binding calculated from a log file.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SourceBinding {
    pub size_bytes: u64,
    pub sha256: String,
}

/// A complete observed result used for manifest comparison.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ObservedValues {
    pub source: SourceBinding,
    pub parser_root_topic: String,
    pub expected: ExpectedValues,
}

/// One stable mismatch between an expectation and an observed result.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Mismatch {
    pub field: String,
    pub expected: String,
    pub actual: String,
}

impl fmt::Display for Mismatch {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            formatter,
            "{}: expected {}, actual {}",
            self.field, self.expected, self.actual
        )
    }
}

/// All output needed by the CLI after parsing and checking one result.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CheckReport {
    pub violations: Vec<String>,
    pub values: Option<ExpectedValues>,
    pub expectation_checked: bool,
}

impl CheckReport {
    /// Whether structural validation and all requested expectation comparisons passed.
    pub fn is_success(&self) -> bool {
        self.violations.is_empty()
    }

    /// Render a compact deterministic success report.
    pub fn success_text(&self) -> Option<String> {
        let values = self.values.as_ref()?;
        if !self.is_success() {
            return None;
        }

        let mut output = String::new();
        output.push_str("check: OK\n");
        if self.expectation_checked {
            output.push_str("expectation: matched\n");
        } else {
            output.push_str("expectation: not supplied (structural only)\n");
        }
        output.push_str(&format!(
            "records: total={} parsed={} ignored={}\n",
            values.records.total, values.records.parsed, values.records.ignored
        ));
        output.push_str(&format!(
            "frames: index={} state={} visualization={} connection={} order={} instant_actions={}\n",
            values.frames.index,
            values.frames.state,
            values.frames.visualization,
            values.frames.connection,
            values.frames.order,
            values.frames.instant_actions
        ));
        output.push_str(&format!("failures: {}\n", format_map(&values.failures)));
        output.push_str(&format!(
            "message_type_distribution: {}\n",
            format_map(&values.message_type_distribution)
        ));
        output.push_str(&format!("unique_robots: {}\n", values.unique_robots));
        match &values.time_range_utc {
            Some(time_range) => output.push_str(&format!(
                "time_range_utc: start={} end={}\n",
                time_range.start.as_deref().unwrap_or("<missing>"),
                time_range.end.as_deref().unwrap_or("<missing>")
            )),
            None => output.push_str("time_range_utc: none\n"),
        }
        Some(output)
    }

    /// Render every structural or semantic mismatch in stable order.
    pub fn failure_text(&self) -> String {
        let mut output = String::from("check: FAILED\n");
        for violation in &self.violations {
            output.push_str("mismatch: ");
            output.push_str(violation);
            output.push('\n');
        }
        output.trim_end().to_string()
    }
}

/// Normalize the root topic to the form used in manifests.
pub fn normalize_root_topic(root_topic: &str) -> Result<String> {
    let normalized = root_topic.trim_end_matches('/');
    if normalized.is_empty() {
        bail!("root topic must not be empty");
    }
    Ok(normalized.to_string())
}

/// Calculate the byte length and SHA-256 digest of a source file.
pub fn source_binding(path: &Path) -> Result<SourceBinding> {
    let file = File::open(path)
        .with_context(|| format!("failed to open source file {}", path.display()))?;
    let size_bytes = file
        .metadata()
        .with_context(|| format!("failed to read metadata for {}", path.display()))?
        .len();

    let mut reader = file;
    let mut hasher = Sha256::new();
    let mut buffer = [0_u8; 64 * 1024];
    loop {
        let bytes_read = reader
            .read(&mut buffer)
            .with_context(|| format!("failed to read source file {}", path.display()))?;
        if bytes_read == 0 {
            break;
        }
        hasher.update(&buffer[..bytes_read]);
    }

    Ok(SourceBinding {
        size_bytes,
        sha256: hex_digest(&hasher.finalize()),
    })
}

/// Derive stable aggregate expectations from a parsed result.
pub fn derive_expected_values(result: &VdaAnalysisResult) -> Result<ExpectedValues> {
    let summary = summarize(result);
    let counts = record_counts(result);
    let frame_counts = canonical_frame_counts(result);

    let message_type_distribution = if frame_counts.index == 0 {
        BTreeMap::new()
    } else {
        let index = result
            .dataframes
            .get("index")
            .context("parser result is missing the index DataFrame")?;
        message_type_distribution_counts(index)
            .context("failed to derive message-type distribution")?
            .into_iter()
            .map(|(message_type, count)| (message_type, count as u64))
            .collect()
    };

    let failures = summary
        .failure_breakdown
        .into_iter()
        .map(|failure| (failure.message_type, failure.count as u64))
        .collect();

    Ok(ExpectedValues {
        records: RecordExpectation {
            total: counts.total_records as u64,
            parsed: counts.parsed_records as u64,
            ignored: counts.ignored_records as u64,
        },
        frames: FrameExpectation {
            index: frame_counts.index as u64,
            state: frame_counts.messages.state as u64,
            visualization: frame_counts.messages.visualization as u64,
            connection: frame_counts.messages.connection as u64,
            order: frame_counts.messages.order as u64,
            instant_actions: frame_counts.messages.instant_actions as u64,
        },
        failures,
        message_type_distribution,
        unique_robots: summary.unique_robots as u64,
        time_range_utc: summary.time_range.map(|time_range| TimeRangeExpectation {
            start: Some(canonical_timestamp(time_range.start.to_rfc3339())),
            end: Some(canonical_timestamp(time_range.end.to_rfc3339())),
        }),
    })
}

/// Build a candidate manifest from a validated parser result.
pub fn build_manifest(
    source_path: &Path,
    root_topic: &str,
    result: &VdaAnalysisResult,
) -> Result<ExpectedManifest> {
    if let Err(errors) = validate_result(result) {
        bail!(errors);
    }
    let root_topic = normalize_root_topic(root_topic)?;
    Ok(ExpectedManifest {
        manifest_version: MANIFEST_VERSION,
        source: source_binding(source_path)?.into(),
        parser: ParserExpectation { root_topic },
        expected: derive_expected_values(result)?,
    })
}

impl From<SourceBinding> for SourceExpectation {
    fn from(binding: SourceBinding) -> Self {
        Self {
            size_bytes: binding.size_bytes,
            sha256: binding.sha256,
        }
    }
}

/// Calculate all values used to compare one parsed result with a manifest.
pub fn observe(
    source_path: &Path,
    root_topic: &str,
    result: &VdaAnalysisResult,
) -> Result<ObservedValues> {
    let root_topic = normalize_root_topic(root_topic)?;
    Ok(ObservedValues {
        source: source_binding(source_path)?,
        parser_root_topic: root_topic,
        expected: derive_expected_values(result)?,
    })
}

/// Validate one parsed result and, when requested, compare it with a manifest.
pub fn check_result(
    result: &VdaAnalysisResult,
    source_path: &Path,
    root_topic: &str,
    expectation_path: Option<&Path>,
) -> Result<CheckReport> {
    let mut violations = match validate_result(result) {
        Ok(()) => Vec::new(),
        Err(errors) => errors.into_violations(),
    };
    let structural_valid = violations.is_empty();
    let expectation_checked = expectation_path.is_some();
    let normalized_root_topic = normalize_root_topic(root_topic)?;
    let mut values = None;

    if let Some(expectation_path) = expectation_path {
        let manifest = read_manifest(expectation_path)?;
        let source = source_binding(source_path)?;

        if structural_valid {
            let observed = ObservedValues {
                source,
                parser_root_topic: normalized_root_topic,
                expected: derive_expected_values(result)?,
            };
            violations.extend(
                compare_manifest(&manifest, &observed)
                    .into_iter()
                    .map(|mismatch| mismatch.to_string()),
            );
            values = Some(observed.expected);
        } else {
            compare_source_and_parser(&mut violations, &manifest, &source, &normalized_root_topic);
        }
    } else if violations.is_empty() {
        values = Some(derive_expected_values(result)?);
    }

    Ok(CheckReport {
        violations,
        values,
        expectation_checked,
    })
}

/// Compare a manifest with an observed result in deterministic field order.
pub fn compare_manifest(manifest: &ExpectedManifest, observed: &ObservedValues) -> Vec<Mismatch> {
    let mut mismatches = Vec::new();

    compare_value(
        &mut mismatches,
        "source.size_bytes",
        manifest.source.size_bytes.to_string(),
        observed.source.size_bytes.to_string(),
    );
    compare_value(
        &mut mismatches,
        "source.sha256",
        manifest.source.sha256.clone(),
        observed.source.sha256.clone(),
    );
    compare_value(
        &mut mismatches,
        "parser.root_topic",
        manifest.parser.root_topic.clone(),
        observed.parser_root_topic.clone(),
    );

    compare_value(
        &mut mismatches,
        "expected.records.total",
        manifest.expected.records.total.to_string(),
        observed.expected.records.total.to_string(),
    );
    compare_value(
        &mut mismatches,
        "expected.records.parsed",
        manifest.expected.records.parsed.to_string(),
        observed.expected.records.parsed.to_string(),
    );
    compare_value(
        &mut mismatches,
        "expected.records.ignored",
        manifest.expected.records.ignored.to_string(),
        observed.expected.records.ignored.to_string(),
    );

    compare_frame_value(
        &mut mismatches,
        "index",
        manifest.expected.frames.index,
        observed.expected.frames.index,
    );
    compare_frame_value(
        &mut mismatches,
        "state",
        manifest.expected.frames.state,
        observed.expected.frames.state,
    );
    compare_frame_value(
        &mut mismatches,
        "visualization",
        manifest.expected.frames.visualization,
        observed.expected.frames.visualization,
    );
    compare_frame_value(
        &mut mismatches,
        "connection",
        manifest.expected.frames.connection,
        observed.expected.frames.connection,
    );
    compare_frame_value(
        &mut mismatches,
        "order",
        manifest.expected.frames.order,
        observed.expected.frames.order,
    );
    compare_frame_value(
        &mut mismatches,
        "instant_actions",
        manifest.expected.frames.instant_actions,
        observed.expected.frames.instant_actions,
    );

    compare_map(
        &mut mismatches,
        "expected.failures",
        &manifest.expected.failures,
        &observed.expected.failures,
    );

    compare_map(
        &mut mismatches,
        "expected.message_type_distribution",
        &manifest.expected.message_type_distribution,
        &observed.expected.message_type_distribution,
    );
    compare_value(
        &mut mismatches,
        "expected.unique_robots",
        manifest.expected.unique_robots.to_string(),
        observed.expected.unique_robots.to_string(),
    );

    let expected_time_range = manifest.expected.time_range_utc.as_ref();
    let actual_time_range = observed.expected.time_range_utc.as_ref();
    compare_optional_value(
        &mut mismatches,
        "expected.time_range_utc.start",
        expected_time_range.and_then(|range| range.start.as_deref()),
        actual_time_range.and_then(|range| range.start.as_deref()),
    );
    compare_optional_value(
        &mut mismatches,
        "expected.time_range_utc.end",
        expected_time_range.and_then(|range| range.end.as_deref()),
        actual_time_range.and_then(|range| range.end.as_deref()),
    );

    mismatches
}

fn compare_source_and_parser(
    violations: &mut Vec<String>,
    manifest: &ExpectedManifest,
    source: &SourceBinding,
    root_topic: &str,
) {
    let mut mismatches = Vec::new();
    compare_value(
        &mut mismatches,
        "source.size_bytes",
        manifest.source.size_bytes.to_string(),
        source.size_bytes.to_string(),
    );
    compare_value(
        &mut mismatches,
        "source.sha256",
        manifest.source.sha256.clone(),
        source.sha256.clone(),
    );
    compare_value(
        &mut mismatches,
        "parser.root_topic",
        manifest.parser.root_topic.clone(),
        root_topic.to_string(),
    );
    violations.extend(mismatches.into_iter().map(|mismatch| mismatch.to_string()));
}

/// Parse and validate one typed expectation manifest.
pub fn read_manifest(path: &Path) -> Result<ExpectedManifest> {
    let contents = fs::read_to_string(path)
        .with_context(|| format!("failed to read expectation manifest {}", path.display()))?;
    let manifest: ExpectedManifest = yaml_serde::from_str(&contents).with_context(|| {
        format!(
            "failed to parse expectation manifest {} (expected exactly one YAML document)",
            path.display()
        )
    })?;
    if manifest.manifest_version != MANIFEST_VERSION {
        bail!(
            "unsupported expectation manifest version {}; expected {}",
            manifest.manifest_version,
            MANIFEST_VERSION
        );
    }
    Ok(manifest)
}

/// Serialize a manifest with a review-status notice and deterministic ordering.
pub fn serialize_manifest(manifest: &ExpectedManifest) -> Result<String> {
    let yaml =
        yaml_serde::to_string(manifest).context("failed to serialize expectation manifest")?;
    Ok(format!("{SNAPSHOT_NOTICE}{yaml}"))
}

/// Write a manifest, refusing an existing target unless explicitly authorized.
pub fn write_manifest(path: &Path, manifest: &ExpectedManifest, overwrite: bool) -> Result<()> {
    if path.exists() && !overwrite {
        bail!(
            "refusing to overwrite existing expectation manifest {}; pass --overwrite (or --force) to opt in",
            path.display()
        );
    }

    let contents = serialize_manifest(manifest)?;
    let mut options = OpenOptions::new();
    options.write(true).create(true);
    if overwrite {
        options.truncate(true);
    } else {
        options.create_new(true);
    }

    let mut file = options
        .open(path)
        .with_context(|| format!("failed to create expectation manifest {}", path.display()))?;
    file.write_all(contents.as_bytes())
        .with_context(|| format!("failed to write expectation manifest {}", path.display()))?;
    Ok(())
}

fn canonical_timestamp(timestamp: String) -> String {
    timestamp
        .strip_suffix("+00:00")
        .map(|prefix| format!("{prefix}Z"))
        .unwrap_or(timestamp)
}

fn hex_digest(digest: &[u8]) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut output = Vec::with_capacity(digest.len() * 2);
    for byte in digest {
        output.push(HEX[usize::from(byte >> 4)]);
        output.push(HEX[usize::from(byte & 0x0f)]);
    }
    String::from_utf8_lossy(&output).into_owned()
}

fn compare_value(mismatches: &mut Vec<Mismatch>, field: &str, expected: String, actual: String) {
    if expected != actual {
        mismatches.push(Mismatch {
            field: field.to_string(),
            expected,
            actual,
        });
    }
}

fn compare_optional_value(
    mismatches: &mut Vec<Mismatch>,
    field: &str,
    expected: Option<&str>,
    actual: Option<&str>,
) {
    if expected != actual {
        mismatches.push(Mismatch {
            field: field.to_string(),
            expected: expected.unwrap_or("<missing>").to_string(),
            actual: actual.unwrap_or("<missing>").to_string(),
        });
    }
}

fn compare_frame_value(
    mismatches: &mut Vec<Mismatch>,
    frame_name: &str,
    expected: u64,
    actual: u64,
) {
    compare_value(
        mismatches,
        &format!("expected.frames.{frame_name}"),
        expected.to_string(),
        actual.to_string(),
    );
}

fn compare_map(
    mismatches: &mut Vec<Mismatch>,
    field_prefix: &str,
    expected: &BTreeMap<String, u64>,
    actual: &BTreeMap<String, u64>,
) {
    let keys: BTreeSet<_> = expected.keys().chain(actual.keys()).collect();
    for key in keys {
        let expected_value = expected.get(key).map(u64::to_string);
        let actual_value = actual.get(key).map(u64::to_string);
        if expected_value != actual_value {
            mismatches.push(Mismatch {
                field: format!("{field_prefix}.{key}"),
                expected: expected_value.unwrap_or_else(|| "<missing>".to_string()),
                actual: actual_value.unwrap_or_else(|| "<missing>".to_string()),
            });
        }
    }
}

fn format_map(values: &BTreeMap<String, u64>) -> String {
    if values.is_empty() {
        return "{}".to_string();
    }
    values
        .iter()
        .map(|(key, value)| format!("{key}={value}"))
        .collect::<Vec<_>>()
        .join(",")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn empty_manifest() -> ExpectedManifest {
        ExpectedManifest {
            manifest_version: MANIFEST_VERSION,
            source: SourceExpectation {
                size_bytes: 0,
                sha256: String::new(),
            },
            parser: ParserExpectation {
                root_topic: "uagv/v1".to_string(),
            },
            expected: ExpectedValues {
                records: RecordExpectation {
                    total: 0,
                    parsed: 0,
                    ignored: 0,
                },
                frames: FrameExpectation {
                    index: 0,
                    state: 0,
                    visualization: 0,
                    connection: 0,
                    order: 0,
                    instant_actions: 0,
                },
                failures: BTreeMap::new(),
                message_type_distribution: BTreeMap::new(),
                unique_robots: 0,
                time_range_utc: None,
            },
        }
    }

    #[test]
    fn manifest_serialization_is_deterministic_and_round_trips() -> Result<()> {
        let manifest = empty_manifest();
        let first = serialize_manifest(&manifest)?;
        let second = serialize_manifest(&manifest)?;
        assert_eq!(first, second);
        let decoded: ExpectedManifest = yaml_serde::from_str(&first)?;
        assert_eq!(decoded, manifest);
        Ok(())
    }

    #[test]
    fn failure_keys_named_start_and_end_remain_numeric() -> Result<()> {
        let mut manifest = empty_manifest();
        manifest.expected.failures.insert("start".to_string(), 1);
        manifest.expected.failures.insert("end".to_string(), 2);

        let yaml = serialize_manifest(&manifest)?;
        let decoded: ExpectedManifest = yaml_serde::from_str(&yaml)?;

        assert_eq!(decoded, manifest);
        assert!(yaml.contains("    start: 1"));
        assert!(yaml.contains("    end: 2"));
        Ok(())
    }

    #[test]
    fn unknown_fields_are_rejected() {
        let yaml = format!(
            "{}\nextra: true\n{}",
            SNAPSHOT_NOTICE.trim_end(),
            yaml_serde::to_string(&empty_manifest()).unwrap_or_default()
        );
        assert!(yaml_serde::from_str::<ExpectedManifest>(&yaml).is_err());
    }

    #[test]
    fn unsupported_versions_are_rejected() -> Result<()> {
        let mut manifest = empty_manifest();
        manifest.manifest_version = 2;
        let path = std::env::temp_dir().join(format!(
            "vda5050-cli-test-unsupported-{}.yaml",
            std::process::id()
        ));
        fs::write(&path, serialize_manifest(&manifest)?)?;
        let result = read_manifest(&path);
        let _ = fs::remove_file(&path);
        assert!(result.is_err());
        assert!(result.err().is_some_and(|error| {
            error
                .to_string()
                .contains("unsupported expectation manifest version")
        }));
        Ok(())
    }

    #[test]
    fn wrong_source_hash_is_reported() {
        let mut observed = ObservedValues {
            source: SourceBinding {
                size_bytes: 1,
                sha256: "actual".to_string(),
            },
            parser_root_topic: "uagv/v1".to_string(),
            expected: empty_manifest().expected,
        };
        let mut manifest = empty_manifest();
        manifest.source.size_bytes = 2;
        manifest.source.sha256 = "expected".to_string();
        let mismatches = compare_manifest(&manifest, &observed);
        assert_eq!(mismatches[0].field, "source.size_bytes");
        assert_eq!(mismatches[1].field, "source.sha256");
        observed.source.sha256 = "expected".to_string();
    }

    #[test]
    fn aggregate_mismatches_are_reported_in_stable_order() {
        let mut manifest = empty_manifest();
        let mut observed = ObservedValues {
            source: SourceBinding {
                size_bytes: 0,
                sha256: String::new(),
            },
            parser_root_topic: "uagv/v1".to_string(),
            expected: empty_manifest().expected,
        };
        manifest.expected.records.parsed = 1;
        manifest.expected.failures.insert("state".to_string(), 2);
        observed.expected.failures.insert("state".to_string(), 1);
        let mismatches = compare_manifest(&manifest, &observed);
        assert_eq!(mismatches[0].field, "expected.records.parsed");
        assert_eq!(mismatches[1].field, "expected.failures.state");
    }
}
